name: Build and Release Android App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: '35.0.0'
        ndk: '23.2.8568313'

    # Grant execute permissions for Gradle wrapper
    - name: Grant execute permissions
      run: chmod +x ./gradlew

    # Build the release APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    # Upload APK/AAB as a build artifact
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Upload Release APK to GitHub Releases
    - name: Upload to GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/debug/*.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive
